version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: googleauth-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  google_auth_service:
    build: .
    container_name: google_auth_service_app
    ports:
      - "8086:8086"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=http://localhost:8086/auth/google/callback
      - JWT_SECRET=${JWT_SECRET:-default-secret-key}
      - UMS_URL=http://user_management_service:8082
      - ALLOWED_EMAILS=${ALLOWED_EMAILS}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
    env_file:
      - .env
